### PR TITLE
CP-15132: Systemd conversion

### PR DESCRIPTION
**Pull request by rafalmiel**
Notify systemd when the daemon is ready

Signed-off-by: Rafal Mielniczuk <rafal.mielniczuk@citrix.com>

### CODE REVIEW

**Comment by robhoes** [comment]
:shipit:  (like xenopsd, this could probably work as `Type=simple`, without notify).

**Comment by robhoes** [comment]
Again, like the others, let's switch to "simple" now, and skip this.

**Comment by rafalmiel** [comment]
Well, that means we don't need to touch this daemon

**Comment by robhoes** [comment]
If you agree with that, then let's just close the PR rather than reverting :)

**Pull request closed without merging**
