### PR TITLE
merge rrddump into xcp-rrdd

### PR DESCRIPTION
**Pull request by lippirk**

### CODE REVIEW

**Comment by lippirk** [comment]
once this is merged (along with https://github.com/xapi-project/xs-opam/pull/443), we can archive https://github.com/xapi-project/rrddump

**Comment by lindig** [comment]
Github warns about conflicts. What is this about?

**Comment by lippirk** [comment]
> Github warns about conflicts. What is this about?

i am not seeing any conflicts in this PR...?

**Comment by lindig** [comment]
I believe: this warning is only about rebase, not merge - because our policy is to rebase and merge.

**Pull request merged**
