### PR TITLE
Remove unused files from the root

### PR DESCRIPTION
**Pull request by psafont**

### CODE REVIEW

**Comment by edwintorok** [comment]
The 'how to submit' changes part from MAINTAINERS could be moved to CONTRIBUTING.md.
To avoid duplicating this file in every repo we should put it into a .github repo as described here though: https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization

**Comment by psafont** [comment]
Building fails without the file `VERSION`, but it's obviously not used as it contains a version from years ago.

**Comment by edwintorok** [comment]
See the dune file, it references the VERSION file (it probably means that it was embedding the wrong version all along).

**Comment by psafont** [comment]
The version number is exposed using `xcp-rrdd --version`. Generating the version from git tags needs more thought and effort from the team (`dune subst` isn't a great fit right now)

I think removing `VERSION` is better left for another PR.

**Comment by lindig** [comment]
Have the comments been addressed? Id so, I'd merge this.

**Comment by psafont** [comment]
Yes, the PR is ready to be merged: the file VERSION is kept as-is for the time being.

**Pull request merged**
