### PR TITLE
CP-13492: Add sr_rrd and rrd_updates http handler for SR-level RRDs

### PR DESCRIPTION
**Pull request by sharady**

### CODE REVIEW

**Comment by johnelse** [comment]
@robhoes and I have been discussing some design problems with the format of the `rrd_updates` parameters - I am writing up a redesign for this.

**Comment by johnelse** [comment]
Sorry for the confusion @sharady - please see the redesign [here](https://github.com/xapi-project/xapi-project.github.io/pull/161). Hopefully this shouldn't be too much work!

**Comment by sharady** [comment]
@johnelse I have updated the PR wrt new design. please have a look thanks.

**Comment by johnelse** [comment]
Whoops, just realised `host=true` used to provide the host *and* VM updates, not just the host updates. We shouldn't change the behaviour of the existing behaviour, even if it seems a bit illogical. I'll update the design again - sorry about this.

**Comment by sharady** [comment]
@johnelse I have modified the PR according to latest design. Please have a look.
Thanks.

**Comment by johnelse** [comment]
This looks good to me. Please squash the third commit into the second and I think we are good to go :)

**Pull request merged**
