### PR TITLE
[specsavers] Merge rrdd-plugins

### PR DESCRIPTION
**Pull request by lippirk**

### CODE REVIEW

**Comment by lindig** [comment]
This merges two repos - I only looked at the commits to make this work and they look good to me. If this builds successfully, it should be good to go.

**Comment by psafont** [comment]
the new directory names are missing a d (`rrdp-...` -> `rrddp-...`)

**Comment by lippirk** [comment]
> the new directory names are missing a d (`rrdp-...` -> `rrddp-...`)

I don't think I changed the names (see the original folders here https://github.com/xenserver/rrdd-plugins/tree/master/src)

**Review by robhoes — APPROVED** [review]

**Comment by psafont** [comment]
> > the new directory names are missing a d (`rrdp-...` -> `rrddp-...`)
> 
> I don't think I changed the names (see the original folders here [https://github.com/xenserver/rrdd-plugins/tree/master/src](https://github.com/xenserver/rrdd-plugins/tree/master/src?rgh-link-date=2021-07-19T12%3A54%3A57Z))

I mean https://github.com/xapi-project/xcp-rrdd/tree/c8b33a75089f86c63aff7e174d8210986fa29677/bin

**Review by psafont — APPROVED** [review]

**Pull request merged**
