### PR TITLE
CA-113824: Prevent "xenapi" bridge datasources creation

### PR DESCRIPTION
**Pull request by ravippandey**

### CODE REVIEW

**Comment by robhoes** [comment]
Some similar code is here: https://github.com/xapi-project/xcp-networkd/blob/master/networkd/network_monitor_thread.ml#L114. It may be better to filter in xcp-networkd already, because it avoids work.

Also, there are a bunch of hardcoded prefixes/patterns for network devices that we do not want to record stats for. It would be nice if we could move those to a config file.

**Comment by ravippandey** [comment]
https://github.com/xapi-project/xcp-networkd/pull/54

**Comment by robhoes** [comment]
Should this be closed on favour of the xcp-networkd PR?

**Comment by ravippandey** [comment]
yes, it think so.

**Pull request closed without merging**
